version: '3'

services:
  vue-app:
    container_name: vue-container
    build:
      context: .
      dockerfile: Dockerfile
    image: vue-chat-app
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
